import type { HarnessResult } from "./schema";

/**
 * src/lib/validateSQL.ts
 * 
 * Goal: Ensure the AI's SQL query is safe to run.
 * Problem: Banning "bad" words is like playing whack-a-mole. It's leaky.
 * Solution: We use a "Physical Lock" (Whitelist). Only approved words are allowed.
 * 
 * @param sql - The SQL string generated by the AI
 * @returns HarnessResult - Our standard "Receipt" confirming if the SQL is safe.
 */

// Approved keywords, tables, and columns allowed to touch our database.
const WHITELIST = [
  // SQL Keywords
  "SELECT", "FROM", "WHERE", "LIMIT", "JOIN", "ON", "AND", "OR",
  "GROUP", "BY", "ORDER", "DESC", "ASC", "AS", "IN", "IS", "NOT", "NULL", "LIKE", "DISTINCT", "COUNT", "SUM", "AVG",
  
  // Tables
  "PROMOTIONS", "SHOW_SERIES", "SHOWS", "WRESTLERS", "MATCHES", 
  "MATCH_PARTICIPANTS", "TITLE_REIGNS", "FACTIONS", "FACTION_MEMBERS",

  // Columns
  "ID", "NAME", "PROMOTION_ID", "SHOW_SERIES_ID", "EVENT_DATE", "LOCATION", "VENUE", "IS_PPV", "ATTENDANCE",
  "CAGEMATCH_ID", "RING_NAME", "GENDER", "BIRTH_DATE", "NATIONALITY",
  "SHOW_ID", "MATCH_ORDER", "WIN_TYPE", "DURATION_SECONDS", "MATCH_TYPE", "TITLE", "IS_TITLE_MATCH", "RATING_NUM",
  "MATCH_ID", "RESULT", "WRESTLER_NAME", "TITLE_NAME", "WON_DATE", "LOST_DATE", "DAYS_HELD", "WON_EVENT", "LOST_TO",
  "ERA", "FACTION_ID"
];

export function validateSQL(sql: string): HarnessResult<{ valid: boolean, sql: string }> {
  const trace: string[] = [];
  const upper = sql.trim().toUpperCase();
  
  try {
    trace.push("Starting security check (Whitelist mode)...");

    // 1. Mandatory SELECT start. No exceptions.
    if (!upper.startsWith("SELECT")) {
      trace.push("FAIL: Query did not start with SELECT.");
      return { success: true, data: { valid: false, sql: "" }, error: "NOT_A_SELECT_QUERY", trace };
    }

    // 2. Mandatory LIMIT. Protects database performance.
    if (!upper.includes("LIMIT")) {
      trace.push("FAIL: Query missing LIMIT clause.");
      return { success: true, data: { valid: false, sql: "" }, error: "MISSING_LIMIT", trace };
    }

    // 3. The "Physical Lock": Check every word against our approved list.
    // We clean up commas and parentheses to find raw keywords.
    const words = upper.split(/[\s,()]+/);
    
    for (const word of words) {
      if (!word) continue;

      // Allow numbers and strings in single quotes (data).
      const isData = !isNaN(Number(word)) || (word.startsWith("'") && word.endsWith("'"));
      
      // If it's not a keyword and not data, it's blocked.
      if (!WHITELIST.includes(word) && !isData) {
        trace.push(`FAIL: Blocked unapproved word/column "${word}".`);
        return { success: true, data: { valid: false, sql: "" }, error: "UNAPPROVED_SQL_ELEMENT", trace };
      }
    }

    trace.push("SUCCESS: SQL passed all security checks.");
    return {
      success: true,
      data: { valid: true, sql: sql.trim() },
      trace
    };

  } catch (err: any) {
    return {
      success: false,
      data: null,
      error: "VALIDATION_CRASH",
      trace: [...trace, `Critical Error: ${err.message}`]
    };
  }
}
